spring.application.name=lostfound

# Supabase PostgreSQL Database
spring.datasource.url=jdbc:postgresql://db.bxkvqhfoiqnlthybagyw.supabase.co:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=passowrd@220205

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Supabase Storage
supabase.url=https://bxkvqhfoiqnlthybagyw.supabase.co
supabase.anon-key=sb_publishable_MQmdeQUL6kr73zNCuGVm1Q_5m_vtvrL
supabase.bucket=item-images

# Logging
logging.config=classpath:logback-spring.xml
logging.level.root=INFO
logging.level.lostofound=DEBUG
logging.file.name=logs/lostfound.log
